site_name: SRE Principles
site_author: c0desta

docs_dir: .

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: README.md
  - Service Level Management: service-level-mgt.md
  - Toil Reduction: toil-reduction.md
  - SRE Pillars:
    - CI/CD Pipelines: 'README.md#cicd-pipelines'
    - Collaboration: 'README.md#collaboration-and-communication'
    - Compliance: 'README.md#compliance-and-auditing'
    - Cost Management: 'README.md#cost-management'
    - Incident Management: 'README.md#incident-management-and-response'
    - Documentation: 'README.md#knowledge-sharing-and-documentation'
    - Monitoring: 'README.md#monitoring-logging-and-alerting'
    - Performance: 'README.md#performance-optimization'
    - Reliability: 'README.md#reliability-and-resilience'
    - Scaling: 'README.md#scaling-and-performance-management'
    - Security: 'README.md#security-best-practices'
