site_name: SRE Principles
copyright: 'Copyright &copy; 2025 <a href="https://github.com/c0desta" target="_blank" rel="noopener">c0desta</a>'
site_author: c0desta



theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - 'Core Concepts':
    - 'Service Level Management': 'service-level-mgt.md'
    - 'Toil Reduction': 'toil-reduction.md'
    - 'Compliance': 'compliance.md'
    - 'Security': 'security.md'
  - 'System Design & Implementation':
    - 'Infrastructure Design': 'infra-design.md'
    - 'CI/CD': 'ci-cd.md'
    - 'Scaling & Performance': 'scaling.md'
    - 'Reliability': 'reliability.md'
  - 'Operations & Response':
    - 'Monitoring & Logging': 'monitoring-logging.md'
    - 'Incident Management': 'incident-mgt.md'
    - 'Collaboration': 'collab.md'
  - 'Optimization & Management':
    - 'Cost Management': 'cost-mgt.md'
    - 'Performance': 'performance.md'
    - 'Optimizations': 'optimizations.md'
    - 'Knowledge Sharing': 'knowledge-base.md'
